services:
  web:
    build: .
    command:
      /app/scripts/start_web.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
